apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tapo-test
  namespace: kubedb-managed
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: tapo-test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: tapo-test
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: tapo-test
  namespace: kubedb-managed
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: tapo-test
  location: eastus
  resourceGroupName: tapo-test
  sshPublicKey: ""
  subscriptionID: 1bfc9f66-316d-433e-b13d-c55589f642ca
  version: v1.24.10
  virtualNetwork:
    cidrBlock: 10.2.0.0/16
    name: tapo-test-vnet
    subnet:
      cidrBlock: 10.2.0.0/16
      name: tapo-test-subnet
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: tapo-test
  namespace: kubedb-managed
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "2"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
  name: tapo-test-pool0
  namespace: kubedb-managed
spec:
  clusterName: tapo-test
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: tapo-test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: tapo-test-pool0
      version: v1.24.10
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: tapo-test-pool0
  namespace: kubedb-managed
spec:
  mode: System
  name: pool0
  scaling:
    maxSize: 2
    minSize: 1
  sku: Standard_D2s_v3
  taints:
  - effect: NoSchedule
    key: CriticalAddonsOnly
    value: "true"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "2"
  name: tapo-test-pool1
  namespace: kubedb-managed
spec:
  clusterName: tapo-test
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: tapo-test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: tapo-test-pool1
      version: v1.24.10
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: tapo-test-pool1
  namespace: kubedb-managed
spec:
  mode: User
  name: pool1
  scaling:
    maxSize: 5
    minSize: 2
  sku: Standard_D2s_v3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: tapo-test
  namespace: kubedb-managed
spec:
  allowedNamespaces: {}
  clientID: 7ee02a15-bccb-4e44-9a97-1b2abbed0926
  clientSecret:
    name: tapo-test-secret
    namespace: kubedb-managed
  tenantID: 772268e5-d940-4bf6-be82-1c4a09a67f5d
  type: ServicePrincipal
